### ISSUE TITLE
make this project installable with HACS

### ISSUE THREAD

**Issue by arska** [anand-p-r/fmi-hass-custom#11]
Hi @anand-p-r 

Awesome project and thanks for publishing!

To make installation & updating easier for users it could make sense to structure the repo so that the integration can be installed with HACS (https://hacs.xyz/docs/faq/custom_repositories). What do you think?

If you agree I'm happy to have a look what would be needed to move around and submit a PR.

Cheers from Turku,
Aarno
![Bildschirmfoto 2021-01-26 um 09 54 40](https://user-images.githubusercontent.com/43398/105823006-54c00b00-5fc5-11eb-97f1-823f44691876.png)

**Comment by anand-p-r** [comment]
Hi @arska 

Sounds good and thanks for offering this! The FMI integration is in the ["Incoming"](https://github.com/home-assistant/core/projects/5#column-10283265) queue of the HASS Core, but I don't know when it will be part of the official release.

In the meantime, it maybe a good idea to get this integrated into HACS. Please go ahead and thanks again!

Regards,
Anand.

**Comment by Din-BH** [comment]
@anand-p-r seems the FMI integration is now in the "Cancelled" queue?

@arska how far off are you with the HACS integration?

BR,
  Björn

**Comment by arska** [comment]
> @arska how far off are you with the HACS integration?

My vacation just started yesterday, so: not very far at all 😂

**Comment by Din-BH** [comment]
@arska any update on this?

**Comment by henripalmroth** [comment]
Would following hacs.json be enough?

`{
  "name": "FMI",
  "content_in_root": true,
  "country": "FI",
  "render_readme": true
}`

**Comment by henripalmroth** [comment]
I made a PR for this: #30

**Comment by anand-p-r** [comment]
@henripalmroth @arska I merged this into master. Please check and see if this is enough for HACS installation.

**Comment by arska** [comment]
Works like a charm, thanks @anand-p-r and @henripalmroth
