### ISSUE TITLE
Wind bearing as a sensor and real FMI sensor data

### ISSUE THREAD

**Issue by joriws** [anand-p-r/fmi-hass-custom#12]
On HA I can see wind speed is just offered as a sensor value. Wind bearing would also be nice like doing automation if Wind is blowing SE and is > 5m/s trigger something.

Also it is not clear if wind speed is some kind of forecast or where it is coming. Please also use API to read actual FMI weather station values. For example "aaltopoiju.fi" service is using those actual sensor values.

**Comment by joriws** [comment]
Also when actual values, wind gust data could be good too

**Comment by henripalmroth** [comment]
I have created REST Sensor to HA for fetching real time date from same API that FMI website uses.

**Comment by joriws** [comment]
Interesting - would you mind sharing the REST sensor config against FMI service.. I might take that route too because live weather is much more important for me than unreliable forecast-data.

**Comment by henripalmroth** [comment]
Sorry. Cannot get the formatting working no matter what. But hopefully you get the idea below.

  - platform: rest
    resource: https://www.ilmatieteenlaitos.fi/api/weather/observations?fmisid=100947&observations=true
    name: Rajakari lämpötila
    scan_interval: 300
    device_class: temperature
    force_update: true
    unit_of_measurement: "°C"
    value_template: '{{ value_json.observations[-1].t2m }}'
    json_attributes_path: "$.observations[-2:-1]"
    json_attributes:
      - name
      - WindSpeedMS
      - WindGust
      - WindDirection
      - Pressure
      - Humidity
      - t2m

And then corresponding template sensors:

 rajakari_wind_direction:
        friendly_name: 'Rajakari tuulen suunta'
        value_template: >-
          {% set wind_dir = state_attr('sensor.rajakari_lampotila', 'WindDirection') %}
          {% if wind_dir | float<=23 %}N
          {% elif wind_dir | float>338 %}N
          {% elif 23 < (wind_dir|float) <=68 %}NE
          {% elif 68 < (wind_dir|float) <=113 %}E
          {% elif 113 < (wind_dir|float) <=158 %}SE
          {% elif 158 < (wind_dir|float) <=203 %}S
          {% elif 203 < (wind_dir|float) <=248 %}SW
          {% elif 248 < (wind_dir|float) <=293 %}W
          {% elif 293 < (wind_dir|float) <=338 %}NW
          {%- endif %}
      rajakari_wind_speed:
        friendly_name: 'Rajakari tuulen nopeus'
        unit_of_measurement: 'm/s'
        value_template: "{{ state_attr('sensor.rajakari_lampotila', 'WindSpeedMS') }}"
        icon_template: 'mdi:weather-windy'
      rajakari_wind_gust:
        friendly_name: 'Rajakari tuulen puuskat'
        unit_of_measurement: 'm/s'
        value_template: "{{ state_attr('sensor.rajakari_lampotila', 'WindGust') }}"
        icon_template: 'mdi:weather-windy'
      rajakari_wind_direction_degrees:
        friendly_name: 'Rajakari tuulen suunta (°)'
        unit_of_measurement: '°'
        value_template: "{{ state_attr('sensor.rajakari_lampotila', 'WindDirection') }}"
        icon_template: 'mdi:weather-windy'
      rajakari_pressure:
        friendly_name: 'Rajakari ilmanpaine'
        unit_of_measurement: 'hPa'
        value_template: "{{ state_attr('sensor.rajakari_lampotila', 'Pressure') }}"
        device_class: pressure
      rajakari_humidity:
        friendly_name: 'Rajakari kosteus'
        unit_of_measurement: '%'
        value_template: "{{ state_attr('sensor.rajakari_lampotila', 'Humidity') }}"
        device_class: humidity

**Comment by joriws** [comment]
Mahtavaa, kiitos teen tolla nyt ensihätään oman toteutukseni myös ja katson tota HA plugin laajennusta joskus kun on aikaa..

**Comment by joriws** [comment]
`
- platform: rest
  name: Siilinkari Last Update
  scan_interval: 600
  force_update: true
  headers:
    Accept-Encoding: gzip, deflate, br
  device_class: temperature
  resource: https://www.ilmatieteenlaitos.fi/api/weather/observations?observations=true&fmisid=101311
  method: GET
  value_template: '{{ value_json.observations[-1].localtime }}'
  json_attributes_path: "$.observations[-2:-1]"
  json_attributes:
    - name
    - WindSpeedMS
    - WindGust
    - WindDirection
    - Pressure
    - Humidity
    - DewPoint
    - t2m
    - localtime

- platform: template
  sensors:
    siilinkari_temperature:
      friendly_name: 'Siilinkari temperature'
      unit_of_measurement: "°C"
      value_template: "{{ state_attr('sensor.siilinkari_last_update', 't2m') }}"  
      icon_template: 'mdi:weather-temperature'
      device_class: temperature
    siilinkari_dewpoint:
      friendly_name:  'Siilinkari dewpoint'
      unit_of_measurement: "°C"
      value_template: "{{ state_attr('sensor.siilinkari_last_update', 'DewPoint') }}"  
      icon_template: 'mdi:weather-temperature'
      device_class: temperature
    siilinkari_wind:
      friendly_name:  'Siilinkari wind speed'
      unit_of_measurement: "m/s"
      value_template: "{{ state_attr('sensor.siilinkari_last_update', 'WindSpeedMS') }}"  
      icon_template: 'mdi:weather-windy'
    siilinkari_gust:
      friendly_name:  'Siilinkari wind gust'
      unit_of_measurement: "m/s"
      value_template: "{{ state_attr('sensor.siilinkari_last_update', 'WindGust') }}"  
      icon_template: 'mdi:weather-windy'
    siilinkari_winddir:
      friendly_name:  'Siilinkari wind direction'
      unit_of_measurement: "°"
      value_template: "{{ state_attr('sensor.siilinkari_last_update', 'WindDirection') }}"  
      icon_template: 'mdi:weather-windy'
    siilinkari_pressure:
      friendly_name:  'Siilinkari pressure'
      unit_of_measurement: "hPa"
      value_template: "{{ state_attr('sensor.siilinkari_last_update', 'Pressure') }}"  
      device_class: pressure
    siilinkari_humidity:
      friendly_name:  'Siilinkari humidity'
      unit_of_measurement: "%"
      value_template: "{{ state_attr('sensor.siilinkari_last_update', 'Humidity') }}"  
      device_class: humidity


`

**Comment by joriws** [comment]
Thanks Henri for the basis - I took forwards from it. Next step is to parametrize it to change something like {% set %} values or something to keep handling of multiple observations simple. I use "sensor: !include_dir_merge_list sensors/" to load files and plan to create new file. Maybe named could also help, need to investigate..

I selected attribute localtime as basis, beucase json_attributes stores everything under then on HA you look at state. Then from that I extract via template the individual values.

**Comment by anand-p-r** [comment]
@joriws : Thanks for trying this out!

I have now added wind direction and wind gust to the sensor as well. Pull the latest release 0.3.0. 

Thanks @henripalmroth for the interpretation of the values. Here's a snapshot of how it looks now.

![image](https://user-images.githubusercontent.com/32978050/110248867-d4a1a380-7f7b-11eb-84a4-ba34eb25a930.png)

The sensor is based on current weather conditions with a refresh interval of 30mins (to keep the API calls within limit). It uses the `async_weather_by_coordinates` API of the [FMI client library](https://pypi.org/project/fmi-weather-client/). So ideally you should be seeing current observations every 30mins.
