### ISSUE TITLE
Error installing fmi integration

### ISSUE THREAD

**Issue by marenl01** [anand-p-r/fmi-hass-custom#13]
Hi!

I get the following error when installing the fmi integration:

"Error occurred loading configuration flow for integration fmi: No module named 'geopy'"

Running latest HassWP

https://github.com/AlexxIT/HassWP v2021.1.1

Br Marenl01

**Comment by anand-p-r** [comment]
@marenl01 I have not tried HassWP, but the error seems to indicate that python package [geopy](https://pypi.org/project/geopy/) is missing on your platform. This is needed for reverse geocoding of the coordinates of the closest lightning strike location. You could try and install the package manually using the instructions at the link above. That should solve the problem.

**Comment by anand-p-r** [comment]
@marenl01 : Have you been able to resolve this?

**Comment by marenl01** [comment]
@anand-p-r : No, not yet. I´ve asked AlexxIT for directions, but haven´t received any yet. I think I will migrate to an linux install since there is also other limitations in HassWP. Maybe I have better luck then. :)
