### ISSUE TITLE
Inconsistency between FMI data and custom component?

### ISSUE THREAD

**Issue by reprz** [anand-p-r/fmi-hass-custom#14]
I noticed that there are differences in weather data between this custom component and FMI data. How does this component define what weather station is being used when GPS coordinates has been used to define place for weather data? For example there are 3 different weather stations in FMI (Pori) and the integration uses which one of those? Here´s some of the data that are not consistent: 

- Temperature in custom component in Pori: -0,3C
- Temperature in Pori Rautatieasema station: -1,8C
- Temperature in Pori lentoasema: -1,9C
- Temperature in Pori Tahkoluoto satama: -1,2C

I tried to search where this -0,3C value is coming from but was unable to find anything. Also the forecast temperatures are different.

*UPDATE* I just found out that FMI API data is different than in https://www.ilmatieteenlaitos.fi/. Is this known issue here?

**Comment by anand-p-r** [comment]
Hi @reprz : The sensor is using this [python library](https://pypi.org/project/fmi-weather-client/) to interface with FMI's open data. This library in turn uses the FMI storedquery_id: [fmi::forecast::hirlam::surface::point::multipointcoverage](https://en.ilmatieteenlaitos.fi/open-data-manual-fmi-wfs-services). I am not expert on how the data is collected and processed before being made available by the open API, but I am guessing that the multipointoverage format uses observations from more than one weather station. While configuring the sensor, you could set the forecast interval to 1, in which case it uses the current observation API to retrieve data from FMI. If the forecast interval is > 1, it uses the weather forecast API to retrieve data from FMI. I am not sure if this answers your question, but this is the best I know :)

**Comment by anand-p-r** [comment]
Closing this, as the component just uses the data provided by the open API.
