### ISSUE TITLE
Sea water height and temperature?

### ISSUE THREAD

**Issue by TheStork239** [anand-p-r/fmi-hass-custom#16]
Would it be possible to add the possibility to have FMI mareograph observations (or forecast) included in the data the add-on fetches, i.e. sea water height and water temperature?

Manually those observations can be queried using the following e.g. for the Helsinki mareograph:
[http://opendata.fmi.fi/wfs?service=WFS&version=2.0.0&request=getFeature&storedquery_id=fmi::observations::mareograph::simple&fmisid=132310&timestep=30](http://opendata.fmi.fi/wfs?service=WFS&version=2.0.0&request=getFeature&storedquery_id=fmi::observations::mareograph::simple&fmisid=132310&timestep=30)

**Comment by TheStork239** [comment]
I've had a go at adding sea water height in a fork:
[https://github.com/TheStork239/fmi-hass-custom](https://github.com/TheStork239/fmi-hass-custom)
I've managed to get the additional sea water height sensors created and it reads the correct data from REST (using the forecast::oaas::sealevel::point::simple FMI query).
However, the sea water level sensors do not seem to update after the initial run and the code gives me runtime warnings from sensor.py:
`'DataUpdateCoordinator.async_request_refresh' was never awaited  self._fmi.async_request_refresh()`

I can't quite figure out where the issue is - any ideas?  I tried to follow the format and structure of the lightning strike sensor.

**Comment by TheStork239** [comment]
Hi,

I got sea water height sensor working in my branch: [https://github.com/TheStork239/fmi-hass-custom](https://github.com/TheStork239/fmi-hass-custom)

It adds a sensor entity showing current sea water height (from the FMI OAAS forecast model, for the latlon location), as well as another for the sea water height 6 hours later, aimed e.g. at the problem of "do I need to pull the rowing boat higher up on the shore at the summer cabin?"
(Obviously the sensor does not work if the latlon location is somewhere inland.)

I'm thinking of adding a sensor entity for the sea water surface temperature from the FMI HBM forecast model, but the geographic forecast area does not seem to come all the way to the shore, so using the latlon of e.g. a location on the coast might need some tinkering to get it to work.

Is it worth merging the sea water height sensor feature into your main branch?

**Comment by anand-p-r** [comment]
@TheStork239 : It's absolutely worth merging it and thanks for extending the integration! Before merging into the main branch, I would still like to regression test all the components. I can try and do it during this week and no later than weekend. Will that be OK?

**Comment by anand-p-r** [comment]
@TheStork239 : Great job with getting all the data and putting the pieces together! 
I made slight adjustments to the code and created a [pull request](https://github.com/anand-p-r/fmi-hass-custom/pull/21). Can you please take a look and confirm if this works for you? I have added comments below in the pull request summarising the changes that includes screenshots of how the sensor would look with the proposed changes. Looking forward to your feedback.

**Comment by TheStork239** [comment]
@anand-p-r : Thanks, looks great and works for me.  Just a minor point of clarity for the readme: the added sensor is overall sea level, not wave height (I think the readme addition says sea wave height).  I guess wave height could be added too, by querying FMI’s WAM wave model data, but that’s probably for another day...

**Comment by anand-p-r** [comment]
Thanks @TheStork239! Fixed and released as version 0.3.2. Please do check and see if all works fine. I will close this issue for now.

**Comment by TheStork239** [comment]
Hi @anand-p-r ,
I think the integrated code to add sea level does not update.  When restarting core HA, it successfully creates the sea level sensor and populates the values, but it does not seem to then refresh the sea height values or forecasts in HA at the 30min intervals.  The log entries suggest that it acquires new values, but they don’t not seem to get reflected in the sensor states.  Could there be something amiss e.g. in the update(self) bit in sensor.py?
I had trouble with that when I was creating the draft code to add the sea level sensor, but in the end got it working by using `self._state = self._fmi.mareo_data.sea_level_now `, rather than `self._state = self.mareo_data.sea_level_now `.  I’m not sure I understand why, and adding the “_fmi” does not seem to work now in the integrated code.
