### ISSUE TITLE
Sea level sensor not updating

### ISSUE THREAD

**Issue by TheStork239** [anand-p-r/fmi-hass-custom#28]
Hi,
I noticed that the sea level sensor is not updating in Home Assistant.  It updates values on restart / initialisation, but the values that the component update pulls from FMI every 30mins don't seem to make their way all the way to be displayed in Home Assistant, so the sensor remains at the initial values.

I got the updating working by editing sensor.py, so that if the 'update(self)' function for the sea level sensor replaces 'self.mareo_data' with 'self._fmi.mareo_data.sea_levels' then it works, e.g. `self._state = self._fmi.mareo_data.sea_levels[0][1]`

**Comment by anand-p-r** [comment]
@TheStork239 Good catch! Looks like `self.mareo_data` is a local variable that gets its value only at init. If we need to update the sensor data periodically, we should use the coordinator object directly, just like you suggested in your solution. Looks like the other sensors are using it this way already. I have fixed this in master branch and tested it. Looks good. Please try it and let me know. This is the [latest release](https://github.com/anand-p-r/fmi-hass-custom/releases/latest).
