### ISSUE TITLE
Integration breaks in core-2021.5.4

### ISSUE THREAD

**Issue by smoltron** [anand-p-r/fmi-hass-custom#31]
After installing Home Assistant core-2021.5.4 the integration breaksi:
`2021-05-15 17:10:40 ERROR (MainThread) [custom_components.fmi-hass-custom] Timeout fetching fmi data`
I do not know if this is caused by the update or if this is a FMI problem. There are however several reports of the problem after update in [https://community.home-assistant.io/t/custom-fmi-finnish-meteorological-institute-weather-sensor-platform/186839/23](https://community.home-assistant.io/t/custom-fmi-finnish-meteorological-institute-weather-sensor-platform/186839/23)

**Comment by henripalmroth** [comment]
I'm still running 2021.4.6 and got the same issue. So I guess it is something else.

**Comment by anand-p-r** [comment]
The Lightning sensor was pulling massive amount of records (79k) causing the intgeration load to increase to 20+secs. The timeout was set at 10secs and hence the errors seen. Probably there has been a surge of lightning strikes, but nature apart, I have bound the record pull to within a limited bounding box of coordinates. I also increased the timeout value for FMI data update, just in case. Do try the [latest version](https://github.com/anand-p-r/fmi-hass-custom/releases/latest) and let me know if that solves the problems seen.

**Comment by henripalmroth** [comment]
Works for me. Thanks again!
