### ISSUE TITLE
Lightning data pull times out, stops all FMI sensors being set up

### ISSUE THREAD

**Issue by TheStork239** [anand-p-r/fmi-hass-custom#42]
With the recent heatwave-related thunderstorms in Finland (in June 2021), the lightning query pulls through quite a big dataset.  As a result, the fetching of lightning data hits the timeout limit, and ends up in a loop of retrying every 90 secs or so, and as a result all of the sensors fail to be set up e.g. on reboot.

Should the timeout limit for lightning data fetch be extended, or should the size of the box be reduced (again/further)?  Or should the code be modified that even if lightning fetch times out, it does not stop the entire FMI set of sensors being set-up / updated?

**Comment by anand-p-r** [comment]
I added a little but of everything now:
- Sensor is disabled by default and can be enabled via UI.
- Bonding box is 500kms now.
- A loop timeout to quit the lightning data setup if it goes beyond 20secs. This can probably be improved later on depending on where it gets stuck.
Remember to clear browser cache to see the new UI option in configuration.
