### ISSUE TITLE
Configuration shows blank

### ISSUE THREAD

**Issue by Ceravyn** [anand-p-r/fmi-hass-custom#44]
Thanks for this project. As a Finnish person this is very useful indeed.

Otherwise working great, however I encountered one slight issue with configuration panel not showing any details for the items, see attached screenshot. Defaults seem to be good for my use, so I didn't need to change these (for now at least).

Home Assistant 2021.10.5
Python 3.9.7
Hassio 5.10.17-v8

![Screenshot_20211019_205523](https://user-images.githubusercontent.com/92232136/137965145-6b3033e1-1560-439b-bbaf-0498027fe67f.png)

**Comment by anand-p-r** [comment]
Hi @Ceravyn,
Thanks!!
Could you try to clean the browser cache and check this again? I have seen this once before after HASS upgrade and cleaning up the browser history, worked in my case.
Do let me know.
Regards,
Anand.

**Comment by Ceravyn** [comment]
@anand-p-r

Hi!

I resolved the issue now when looking more into it. In my case this was due to git clone defaults into "custom_components/fmi-hass-custom/..." based on repo name and directory paths in .py's requiring files to be in "custom_components/fmi/..." so it has to be manually changed.

Basic functionality worked even with the wrong directory of install so it went unnoticed while I was just using the basic weather card for current weather. I did notice now that the correct path of installation reads in the instructions, so yeah, user error. :)

**Comment by Arkkimaagi** [comment]
Nope, I get the same problem, my folder is `custom_components/fmi/` I even tried in another browser where I have not used home assistant before.

**Comment by Arkkimaagi** [comment]
If there would be a screenshot of what it should look like, I could adjust the parameters even if it's not working currently.

**Comment by anand-p-r** [comment]
@Arkkimaagi I was again unable to reproduce the problem. However I have updated the installation instructions to clarify on the folder name to be used. Sometime later, I will try a greenfield installation of HASS with the custom component and see if it helps finding any deployment issues.
