### ISSUE TITLE
A fix needed for 2022.3 and onwards

### ISSUE THREAD

**Issue by kontiainen** [anand-p-r/fmi-hass-custom#50]
Configuration -> Logs reports this:

"Detected code that uses str for device registry entry_type. This is deprecated and will stop working in Home Assistant 2022.3, it should be updated to use DeviceEntryType instead. Please report this issue."

It looks like this type of definition is found in weather.py file.

**Comment by anand-p-r** [comment]
@slovdahl Thanks for taking care of this! @kontiainen Please try the new [release](https://github.com/anand-p-r/fmi-hass-custom/releases/tag/v0.4.8) and see if the warnings disappear. Thanks!!

**Comment by kontiainen** [comment]
All good. Thank you, @anand-p-r!
