### ISSUE TITLE
Usage of deprecated method, unsupported HA 2023.1 onwards

### ISSUE THREAD

**Issue by Kuitsi** [anand-p-r/fmi-hass-custom#57]
/config/logs says:

custom_components.fmi.weather::FMIWeatherEntity is overriding deprecated methods on an instance of WeatherEntity, this is not valid and will be unsupported from Home Assistant 2023.1. Please report it to the custom integration author

**Comment by TheStork239** [comment]
@anand-p-r is this something on your radar?  What is the deprecated method used, and how much of a heavy lift will it be to fix?

**Comment by TheStork239** [comment]
I think this is the issue:
https://developers.home-assistant.io/blog/2022/06/27/weather_entity_refactoring/
