### ISSUE TITLE
Library fmi-weather-client might stop working after September 2022

### ISSUE THREAD

**Issue by T3m3z** [anand-p-r/fmi-hass-custom#61]
Hello and thank You for this custom component! I am writing to notify You that the python library fmi-weather-client, used by this custom component, is using old Hirlam weather model.

From FMI website (https://en.ilmatieteenlaitos.fi/hirlam-opendata-on-aws-s3):

>The use of the HIRLAM weather forecasting model at the Finnish Meteorological Institute will be discontinued in September 2022, after which its forecasts are no longer available through the open data services.
>
>During the past fifteen years, the main focus in forecast model development has been on a more accurate model with improved resolution. The resulting HARMONIE (MEPS) model is capable of 2.5 km horizontal resolution (compared to 7.5 km of HIRLAM) and able to predict small scale phenomena more accurately. HARMONIE (MEPS) forecasts are now available through the open data services.
>
>More information will be made available later, but already now it is worth switching to use HARMONIE (MEPS) model if possible.
>

It seems that the library is using soon to be removed Hirlam model: https://github.com/saaste/fmi-weather-client/blob/master/fmi_weather_client/http.py#L100

I have already opened https://github.com/saaste/fmi-weather-client/issues/39 and https://github.com/saaste/fmi-weather-client/pull/40 .

**Comment by TheStork239** [comment]
The FMI component still seems to work, even after the end of September.  @T3m3z  do you know if the underlying library was fixed / updated and therefore this is no longer a concern?

**Comment by T3m3z** [comment]
Sorry for delayed answer. Finnish Meteorological Institute has updated page linked in the original message:
>The use of the HIRLAM weather forecasting model at the Finnish Meteorological Institute will be discontinued in the end of **October 2022**, after which its forecasts are no longer available through AWS. HARMONIE (MEPS) forecasts are now available through our own open data services.

Saaste has implemented a new version of the fmi-weather-client library (version 0.1.2), which uses the new Harmonie model. If this custom component stops working, you should be able to move to use the new version of the library by editing manifest.json row 7 to be
>"fmi-weather-client==**0.1.2**",
