### ISSUE TITLE
Daily forecast icon matches the FMI icon for the time 00:00.

### ISSUE THREAD

**Issue by t-muki** [anand-p-r/fmi-hass-custom#63]
The daily forecast shows the icon from the corresponding day's midnight, not the one that represents the day. For example at the moment saturday is shown as cloudy in helsinki although the FMI forecast says saturday will be sunny.

**Comment by cruwaller** [comment]
I noticed the same issue and I was debugging this a bit. Looks like the fmi's opendata returns a bit different symbol values for a weird reason. So, there is nothing we can do for this.
