### ISSUE TITLE
Sea water height data no longer works

### ISSUE THREAD

**Issue by TheStork239** [anand-p-r/fmi-hass-custom#64]
It seems that FMI have made some change in the open data query for OAAS sea water height data, and the existing code stopped providing sea water level data around the 10th January.  I cannot find any explanation on FMI Open Data website to OAAS data provision, but by trial and error I noticed that a slight change in the query will make it work again.  I have also queried with FMI Open Data if they can provide more information.

In the meantime, it seems that the WFS queries for "fmi::forecast::oaas::sealevel::point::simple" now result in a "handler not found" error in the xml response to the query.  But if that is amended to fmi::forecast::sealevel::point::simple" then it works.

Therefore, at least for now, this issue can be addressed by modifying row 66 in const.py to the following, i.e. removing "OAAS" from the query format:
`BASE_MAREO_FORC_URL = "http://opendata.fmi.fi/wfs?service=WFS&version=2.0.0&request=getFeature&storedquery_id=fmi::forecast::sealevel::point::simple&timestep=30&"`

**Comment by TheStork239** [comment]
I got a response from FMI.  OAAS provision has indeed been stopped as part of phasing our Hiram weather models.  I have created a pull request that uses an updated URL that works: #65 
Hope that is useful.

**Comment by cruwaller** [comment]
Fixed by #65.
