### ISSUE TITLE
New release 2023.9 will abandon forecast attribute for weather entities

### ISSUE THREAD

**Issue by fursov** [anand-p-r/fmi-hass-custom#68]
https://www.home-assistant.io/blog/2023/09/06/release-20239/#weather-forecast-service

So the warning reported on my setup:
```
Logger: homeassistant.components.weather
Source: components/weather/__init__.py:339
Integration: Weather (documentation, issues)
First occurred: 08:54:47 (1 occurrences)
Last logged: 08:54:47

custom_components.fmi.weather::None is using a forecast attribute on an instance of WeatherEntity, this is deprecated and will be unsupported from Home Assistant 2024.3. Please report it to the custom integration author.
```
I think you noticed this issue yourself so I decided to create the ticket for tracking purposes only :)

**Comment by Hiekkaharju** [comment]
I just want to suggest that this change would be done in tho phases = releases. First one asap - add support for the new service for getting the forecast. Second just before the attribute deprecation actually happens - remove the attribute. This way we users have some time to move to use the service and the attribute still works while we implement and test our changes. That would be especially good for those of us who use the forecast in automations.

**Comment by oleg-d** [comment]
![image](https://github.com/anand-p-r/fmi-hass-custom/assets/25592559/bbb0c994-546b-4cca-a85c-5d8529f5269c)

**Comment by cruwaller** [comment]
@anand-p-r any update / comment?

**Comment by cruwaller** [comment]
@anand-p-r please check my PR for fix to this... Or let me know if you think something needs to be changed.

**Comment by boozeman** [comment]
I hope @anand-p-r is fine and everything is ok. I hope this is just because he doesn't have time to maintain the repository

**Comment by cruwaller** [comment]
@anand-p-r happy to hear from you and you are ok! 
I created an organization to track your great work further. It will be easier for you and users to follow...
I added you as owner. 
Maybe you could even move this repository to there? (and I will remove the existing fork)
