### ISSUE TITLE
Still no state_class

### ISSUE THREAD

**Issue by MarkoPaasila** [anand-p-r/fmi-hass-custom#72]
https://github.com/anand-p-r/fmi-hass-custom/issues/60 is closed but none of the sensors have a `state_class: measurement` attribute. Statistics don't work without it.

**Comment by cruwaller** [comment]
Sorry for a long delay... 
This is a pretty clear issue and missing `state_class` property from other than `FMIMareoSensor` sensor.
I will modify the code.

**Comment by cruwaller** [comment]
Could you try PR #74 ?
