### ISSUE TITLE
Parsing error with release 2024.10.2

### ISSUE THREAD

**Issue by fursov** [anand-p-r/fmi-hass-custom#76]
This is related to https://github.com/saaste/fmi-weather-client/issues/58, update will be required to the newer library

**Comment by fursov** [comment]
Now there is fmi-weather-client library release 0.4.0 is available, I checked and it works with 2024.10.2. Please, take this in use.

**Comment by oleg-d** [comment]
I think fix is to just use latest library right https://github.com/anand-p-r/fmi-hass-custom/pull/77
locally it worked for me.

**Comment by tsimola** [comment]
Looks like it is working from 2024.10.3 onwards.

**Comment by cruwaller** [comment]
Just triggered a new release so close this now.
