### ISSUE TITLE
Incorrect wind speeds in forecasts

### ISSUE THREAD

**Issue by JuusoOikarinen** [anand-p-r/fmi-hass-custom#79]
Wind speeds for weather forecasts appear to be incorrect.

This seems to be due to the fact that the fmi-weather-client returns forecast wind speeds in m/s, which are passed directly to home assistant which expects km/h.

In my deployment, I added a multiplication of 3.6 to convert m/s to km/h in weather.py _forecast (rows 217 and 240) and that seems to fix the issue for me.

**Comment by cruwaller** [comment]
Ok, good catch and analyse!
Could you open a PR for a fix?

**Comment by JuusoOikarinen** [comment]
I'm completely unfamiliar with github practices, but I did give a PR a shot.

**Comment by cruwaller** [comment]
As explained in #80 I will close this now. Just open a new ticker later if needed.
