### ISSUE TITLE
[Wishlist] HACS integration of the FMI-HASS component

### ISSUE THREAD

**Issue by jkk-jkk** [anand-p-r/fmi-hass-custom#8]
Hi,

You have done excellent job with your component. I'm hoping that you would at some stage find time to integrate it to HACS for more streamlined handling of your component.

I do admit that it does most likely require some additional work from your side unfortunately.

https://hacs.xyz/docs/publish/start

Happy new year!

P.S. First time I'm creating issue in public github so hopefully this was good enough.

**Comment by anand-p-r** [comment]
Happy New Year!!

This integration is halfway through to being part of the core.
https://github.com/home-assistant/core/projects/5#column-10283265

If it takes too long, I will try and add this HACS.

**Comment by jkk-jkk** [comment]
Excellent news! Thanks.
